import React from 'react';
import About1 from 'D:/hello world/Programming/new project/sfmm_sg/src/images/carbon.jpeg'; // Adjust the path as necessary
import './About.css'; // Ensure this path is correct and the CSS file is in the same directory

const About = () => {
  return (
    <div id='about' className='about-section'>
      <div className='about-image'>
        <img src={About1} alt='About Us' />
      </div>
      <div className='about-text'>
        <h1>LEARN MORE ABOUT US</h1>
        <p>
          A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) 
          that are generated by our actions. The average carbon footprint for a person in the United States is 16 tons, 
          one of the highest rates in the world. Globally, the average carbon footprint is closer to 4 tons. To have 
          the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year 
          needs to drop to under 2 tons by 2050.
        </p>
        <a href="https://en.wikipedia.org/wiki/Carbon_footprint" target="_blank" rel="noopener noreferrer">
          <button className="cool-button">READ MORE</button>
        </a>
      </div>
    </div>
  );
}

export default About;